print ("Please type your name in")
my_name = input ()
print("Nice to meet you ", my_name)
print("So ", my_name, "what is your favourite food?")
favourite_food = input ()
print("ah, your favourite food is", favourite_food)
print("How old are you?")
my_age = input ()
print("Oh really!")
my_con = input ()
print("where are you live")
my_address = input ()
print("how is your life?")
my_answer = input ()
print("Good to hear")
my_answer = input ()
print("so what is your dream?")
my_answer = input ()
print("pretty good dream")
my_answer = input ()
print("ok bye bye")
my_answer = input ()
